version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: deployment/scripts/stop_container.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: deployment/scripts/start_container.sh
      timeout: 300
      runas: root
